/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbconnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author laizer corp
 */
public class FareForm extends javax.swing.JFrame {

    /**
     * Creates new form FareForm
     */
    
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    ResultSetMetaData resInfo = null;
    
    JOptionPane pane = new JOptionPane();
    
    public FareForm() {
        initComponents();
            
        fillCBStartItems();
        fillCBEndItems();
    }
    
    private void populateFare(){
        int fare = 0;
        
        try{
            String url = "SELECT fare FROM routes WHERE start=? and destination=? and class=?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_db?","root","");
            ps = conn.prepareStatement(url);
            ps.setString(1, cb_start.getSelectedItem().toString());
            ps.setString(2, cb_end.getSelectedItem().toString());
            ps.setInt(3, cb_class.getSelectedIndex()+1);

            rs = ps.executeQuery();

            if(rs.next()){
                fare = rs.getInt(1);
//                System.out.println(fare);
            }
        }
        catch(Exception ex){
            pane.showMessageDialog(null, ex.getMessage(), "Error" ,pane.ERROR_MESSAGE);
        }
        
        lbl_busfare.setText(Integer.toString(fare));
    }
    
    private void fillCBStartItems(){
        try{
            String url = "SELECT DISTINCT start FROM routes";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_db?","root","");
            ps = conn.prepareStatement(url);

            rs = ps.executeQuery();
//            resInfo = rs.getMetaData();

            ArrayList<String> items = new ArrayList<>();
            
            int i=0;
            while(rs.next()){
//                pane.showMessageDialog(null,rs.getString(1) , "Query Done!" ,pane.INFORMATION_MESSAGE);
                items.add(rs.getString(1));
                i++;
            }
            
            String[] cbItems = items.toArray(new String[0]);
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>( cbItems );
            cb_start.setModel(model);

        }
        catch(Exception ex){
            pane.showMessageDialog(null, ex.getMessage(), "Error" ,pane.ERROR_MESSAGE);
        }
    }
    
    private void fillCBEndItems(){
        try{
            String url = "SELECT distinct destination FROM routes WHERE start=?";
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_db?","root","");
            ps = conn.prepareStatement(url);
            ps.setString(1, cb_start.getSelectedItem().toString());

            rs = ps.executeQuery();

//            String items[] = new String[rs.getFetchSize()];
//            System.out.println(rs.getArray("destination").getArray());
            ArrayList<String> items = new ArrayList<>();
            
            int j=0;
            while(rs.next()){
//                System.out.println(cb_start.getSelectedItem().toString()+" -> "+rs.getString(1));
                items.add(rs.getString(1));
                j++;
            }
            String[] cbItems = items.toArray(new String[0]);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(cbItems);
            cb_end.setModel(model);

        }
        catch(Exception ex){
            pane.showMessageDialog(null, ex.getMessage(), "Error" ,pane.ERROR_MESSAGE);
        }
        
        populateFare();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        cb_end = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_start = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_busfare = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb_class = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bus Fare");
        setLocation(new java.awt.Point(450, 250));

        cb_end.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_end.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_endItemStateChanged(evt);
            }
        });
        cb_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_endActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("End");

        cb_start.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_start.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_startItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Start");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Route Details");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Bus Class");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Bus Fare");

        lbl_busfare.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Tsh");

        cb_class.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb_class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Class", "Second Class", "Third Class" }));
        cb_class.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_classItemStateChanged(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_busfare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addComponent(cb_class, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(cb_start, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_end, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_busfare)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_endActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_endActionPerformed

    private void cb_startItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_startItemStateChanged
        // TODO add your handling code here:
        fillCBEndItems();
    }//GEN-LAST:event_cb_startItemStateChanged

    private void cb_classItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_classItemStateChanged
        // TODO add your handling code here:
        populateFare();
    }//GEN-LAST:event_cb_classItemStateChanged

    private void cb_endItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_endItemStateChanged
        // TODO add your handling code here:
        populateFare();
    }//GEN-LAST:event_cb_endItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new SeatForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FareForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FareForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_class;
    private javax.swing.JComboBox<String> cb_end;
    private javax.swing.JComboBox<String> cb_start;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_busfare;
    // End of variables declaration//GEN-END:variables
}
